### ISSUE TITLE
jcenterRepo does not have the artifacts

### ISSUE THREAD

**Issue by suriyanto** [jodersky/sbt-jni#1]
I am trying to pull the artifacts from jcenterRepo (https://jcenter.bintray.com) but can't seem to be able to find this artifact (https://jcenter.bintray.com/ch/jodersky/).

Am I missing anything?

**Comment by jodersky** [comment]
I'm sorting things out with bintray (got a message saying the package already exists, however as far as I checked that's not true).

As a workaround try adding `resolvers += Resolver.bintrayRepo("jodersky", "maven")` to your `build.sbt`

**Comment by suriyanto** [comment]
Thanks very much for the workaround. It would have worked except that my project have dependency for Scala 2.10. Would you happen to have a 2.10 version available?

**Comment by jodersky** [comment]
Just got a message from bintray, the repo is in JCenter now (so no more need for the workaround, things *should* just work).

Regarding your dependency to Scala 2.10, only `JniLoad` is affected, other plugins do not depend on any Scala versions. The reason why 2.10 is not supported is because JniLoad uses quasiquotes, a feature made officially part of Scala in 2.11.

I would strongly advise you to upgrade to Scala 2.11 (if that's in your hands) since 2.10 reached EOL almost a year ago. However, if that is not an option, I can see two possible solutions:

1. Deactivate the plugin `disablePlugin(JniLoad)`, however you will lose most of `sbt-jni`'s benefits IMO
2. Check out the [quasiquote docs](http://docs.scala-lang.org/overviews/quasiquotes/setup#sbt-cross-compile), it seems as though there is actually an easy way to support Scala 2.10 as well. I'd welcome a patch to support it!

**Comment by suriyanto** [comment]
Thanks very much. It's working now after the plugin is disabled. There's a bit typo for `disablePlugin(JniLoad)`. It should be `disablePlugins(JniLoad)`. I'll do a quick doc PR in a bit.

**Comment by jodersky** [comment]
Cool thx, I'm also just in the process of reviewing the readme
