### ISSUE TITLE
Plugin is looking for ch.jodersky#sbt-jni-macros_2.10;1.0.0-RC1 for Scala 2.10

### ISSUE THREAD

**Issue by suriyanto** [jodersky/sbt-jni#2]
After performing publishLocal, the plugin is published locally for both 2.10 and 2.11 under 2 different directory: `sbt-jni` and `sbt-jni-macros_2.11`.

However when I add the plugin for Scala 2.10 project:
`addSbtPlugin("ch.jodersky" % "sbt-jni" % "1.0.0-RC1")`

it is actually looking for `ch.jodersky#sbt-jni-macros_2.10;1.0.0-RC1`. I wonder on the extra `-macros` on what it is looking for.

**Comment by jodersky** [comment]
`sbt-jni` consists of two sbt projects:

1. The first one (in `plugins/)` contains all the AutoPlugins (JniJavah, JniLoad, JniNative and JniPackage) that are enabled in user projects who have added `addSbtPlugin("ch.jodersky" % "sbt-jni" % "1.0.0-RC1")` to their plugin configuration. This project is only built against Scala 2.10, since that is the scala version that sbt uses internally. The classes in these plugins will be available to the user's build, however their own project's sourcecode will not be touch with them. You can think of this as the "real" sbt-jni plugin.

2. The second project (in `macros/`) contains an annotation that can be added in user's project's sourcecode to inject a transparent, native loading function akin to the standard java `System.load`. Since it will be used in actual project source code, it is cross-compiled for multiple scala versions, 2.10 not being part of it, as I explained in #1. Now, to give user code access to the this annotation, all you need to do is add the dependency `libraryDependencies += "ch.jodersky" %% "sbt-jni-macors" % "1.0.0-RC1" % Provided` to any relevant build definition (you'll also need to add the macros paradise dependency, but it's the same idea). The plugin `JniLoad` is just a shorthand to add that dependency to projects. In fact, you can [check out the code](https://github.com/jodersky/sbt-jni/blob/791cb363b77332e3abdf4039102dfcdb863ce6c3/plugin/src/main/scala/ch/jodersky/sbt/jni/plugins/JniLoad.scala) that will be added to projects, it's pretty simple

The problem you are experiencing is that your project is using Scala 2.10 and has `JniLoad` enabled. `JniLoad` will then add the `sbt-jni-macros` library to your project's dependencies which doesn't exist for scala 2.10.
I hope that explains what is going on behind the scenes. As you may have guessed, this project is still pretty much in beta and lacking documentation. Thanks for asking these questions!
