### ISSUE TITLE
Release for sbt 1.0

### ISSUE THREAD

**Issue by ktoso** [jodersky/sbt-jni#24]
Would be nice to see a release for sbt 1.0

**Comment by jodersky** [comment]
It's already available with sbt-jni version 1.3.0-M1 (and source is in branch `sbt-1`). I haven't released a final version yet, since sbt-jni is affected by an upstream bug and I haven't been able to extensively test [the workaround](https://github.com/jodersky/sbt-jni/pull/23#issuecomment-322014447) yet.

**Comment by jodersky** [comment]
workaround fixed with an upgrade to sbt 1.0.1, used in version 1.3.0
