### ISSUE TITLE
got error running nativeInit, but no error message printed

### ISSUE THREAD

**Issue by jeanjluo** [jodersky/sbt-jni#25]
$ sbt nativeInit cmake
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/jeanluo/test/sbt_jni/project
[info] Loading settings from build.sbt ...
[info] Set current project to sbt_jni (in build file:/Users/jeanluo/test/sbt_jni/)
[error] Total time: 0 s, completed Nov 14, 2017 11:32:15 AM

macOs: 10.12.6
sbt_jni: 1.3.0
sbt: 1.0.2

builds.sbt
import Dependencies._

lazy val root = (project in file("."))
  .enablePlugins(JniNative)
  .settings(
    inThisBuild(List(
      organization := "com.example",
      scalaVersion := "2.12.3",
      version      := "0.1.0-SNAPSHOT"
    )),
    name := "sbt_jni_test",
    libraryDependencies += scalaTest % Test
  )
~

**Comment by jodersky** [comment]
The build file seems fine. Can you double-check that the cmake file is not created (it should be in `src/native/`)?
In case it is indeed an error, could you try running sbt with a more verbose debug level? In the sbt interactive shell type `last nativeInit` to get a log if the command. In case that doesn't give anything useful. try running sbt with the `--debug` flag.

**Comment by jeanjluo** [comment]
Thanks for the suggestion to use the sbt interactive shell. I found the cmake file got successfully generated  if I used the interactive shell.

> sbt:sbt_jni> nativeInit cmake adder0
[info] Initializing native build with CMake configuration
[info] Wrote to /Users/jeanluo/test/sbt_jni/src/native/CMakeLists.txt
[success] Total time: 0 s, completed Nov 14, 2017 3:49:05 PM

However, no cmake file is generated if I run "sbt nativeInit cmake" at the command prompt of my terminal. Not sure what is causing this different behavior.

**Comment by jodersky** [comment]
sbt has a weird way in handling spaces in command line arguments. Basically, each argument to sbt is expected to be a task or command, so that you can chain operations such as `sbt clean test`. This behavior however makes it impossible for sbt to distinguish if an argument is a task or itself an argument to a a task. In order to work around that, all task-argument associations need to wrapped in double quotes I.e. in this case the correct incantation would be `sbt "nativeInit cmake`.

**Comment by jeanjluo** [comment]
Adding double quotes works! Thank you!
